version: '3.8'

services:
  scribbly.eventually.example.api:
    image: scribbly.eventually.example.api
    build:
      context: .
      dockerfile: example/Scribbly.Eventually.Example.Api/Dockerfile

  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
