FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["example/Scribbly.Eventually.Example.Api/Scribbly.Eventually.Example.Api.csproj", "example/Scribbly.Eventually.Example.Api/"]
RUN dotnet restore "example/Scribbly.Eventually.Example.Api/Scribbly.Eventually.Example.Api.csproj"
COPY . .
WORKDIR "/src/example/Scribbly.Eventually.Example.Api"
RUN dotnet build "Scribbly.Eventually.Example.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Scribbly.Eventually.Example.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Scribbly.Eventually.Example.Api.dll"]
